name: Build Mine DS Game
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Compile the game
        run: |
          # Finds the Makefile even if tucked inside a subfolder
          if [ -f "Makefile" ]; then
            echo "Makefile found in root."
          elif [ -d "mine-ds-master" ]; then
            cd mine-ds-master
          elif [ -d "mine-ds-main" ]; then
            cd mine-ds-main
          else
            cd *
          fi
          make clean
          make

      - name: Upload Completed NDS File
        uses: actions/upload-artifact@v4
        with:
          name: ZombieFree-MineDS
          path: |
            ./*.nds
            ./**/*.nds
